  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - uses: actions/checkout@v3

      - name: Run foo
        uses: docker://foo-image
        with: 
          args: /foo-script
